/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class energymeasure_EnergyReading */

#ifndef _Included_energymeasure_EnergyReading
#define _Included_energymeasure_EnergyReading
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     energymeasure_EnergyReading
 * Method:    measureEnergy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_energymeasure_EnergyReading_measureEnergy
  (JNIEnv *, jobject);

/*
 * Class:     energymeasure_EnergyReading
 * Method:    setAffinity
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_energymeasure_EnergyReading_setAffinity
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     energymeasure_EnergyReading
 * Method:    getAffinity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_energymeasure_EnergyReading_getAffinity
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
